/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 515877d272dfd3b0f9c2aa2a4f4cca49)
interface __BaseEnv_Env {
	DEEPSEEK_API_KEY: string;
	DEEPSEEK_MODEL: string;
	TaskAgent: DurableObjectNamespace<import("./src/server").TaskAgent>;
	Sandbox: DurableObjectNamespace<import("./src/server").Sandbox>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "TaskAgent" | "Sandbox";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DEEPSEEK_API_KEY" | "DEEPSEEK_MODEL">> {}
}
