/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: defbe7170eeb8b5d0ad3e0b30a2f32d0)
interface __BaseEnv_Env {
	DEEPSEEK_API_KEY: string;
	DEEPSEEK_MODEL: string;
	VUILABS_API_KEY: string;
	TaskAgent: DurableObjectNamespace<import("./src/server").TaskAgent>;
	TaskRegistry: DurableObjectNamespace<import("./src/server").TaskRegistry>;
	Sandbox: DurableObjectNamespace<import("./src/server").Sandbox>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "TaskAgent" | "Sandbox" | "TaskRegistry";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DEEPSEEK_API_KEY" | "DEEPSEEK_MODEL">> {}
}
