/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 85e2f2b5c2e029c10cd79305cf1a9a43)
interface __BaseEnv_Env {
	BACKUP_BUCKET: R2Bucket;
	BACKUP_BUCKET_NAME: "cloud-agent-backups";
	CLOUDFLARE_ACCOUNT_ID: "42858c96007b726ffb88ee5e50eed404";
	DEEPSEEK_API_KEY: string;
	DEEPSEEK_MODEL: string;
	VUILABS_API_KEY: string;
	TaskAgent: DurableObjectNamespace<import("./src/server").TaskAgent>;
	TaskRegistry: DurableObjectNamespace<import("./src/server").TaskRegistry>;
	Sandbox: DurableObjectNamespace<import("./src/server").Sandbox>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "TaskAgent" | "Sandbox" | "TaskRegistry";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BACKUP_BUCKET_NAME" | "CLOUDFLARE_ACCOUNT_ID" | "DEEPSEEK_API_KEY" | "DEEPSEEK_MODEL" | "VUILABS_API_KEY">> {}
}
